### PR TITLE
Updated dependencies to support API 6702

### PR DESCRIPTION
**Pull request by deivuh**

### CODE REVIEW

**Comment by ghost** [comment]
How do i get this to work now?

**Comment by YesThatAllen** [comment]
I was able to use 

```
yarn
yarn run dev
```

on this branch, and it allowed me to log in (I did nothing else past that)

**Comment by ghost** [comment]
It doesn't even allow me to start the app.

**Comment by YesThatAllen** [comment]
@therealabradolf if you're trying to compile the app from this branch, let us know specifically what you've tried and what errors you are seeing.

This built on my Mac running 10.12, I'm sure once we have confirmation that it's working on other platforms, @vinnymac will be able to merge & post a release for general usage.


PS my steps were to check out deivuh's branch, and in terminal I brew-upgraded then

```
yarn
yarn run dev
changed the api to 6702
```

Of course, there's a new API version releasing today, so there's no telling if this will continue to work.. it is out of our control.

**Comment by vinnymac** [comment]
I am gonna merge this, but we need 6900 now anyways.

**Pull request merged**
