### PR TITLE
Add support for display options

### PR DESCRIPTION
**Pull request by hacknug**
# To-do
- [x] Use female sprites
- [x] Add shiny Magikarp and Gyarados animated sprites
- [ ] Add display options to details modal

Is there anything else you would like to see added to this?

### CODE REVIEW

**Comment by YesThatAllen** [comment]
What goodness does this bring?
> Add display options to details modal

Showing the IV components (15/14/13) etc to the modal would be a nice add

**Comment by hacknug** [comment]
It would show you if a mon uses a different costume/skin than default, is male/female/genderless, is shiny or not, and what's its form (Unowns have 28 different ones).

**Comment by vinnymac** [comment]
I don't think we show gender anywhere, so maybe we can use the gender symbols for it and put it in the modal somewhere. You can create checkboxes in the GitHub markdown using brackets [] in a list if you wanted to keep track of what you've done.

Good usage of node-pogo-protos by the way, idk if we are missing any edge cases but I am sure we will find out.

This would be a lot harder, but i think it is possible for us to show the actual HP in the modal.

**Comment by Redarion** [comment]
The actual hp are in the pokemon info from pogo, so I don't think it's difficult to add a new display with that info

**Comment by vinnymac** [comment]
Harder in terms of amount of work. It'll be more work to design an HP gauge that represents the current HP than to display a symbol in the modal for gender.

**Comment by hacknug** [comment]
I really don't understand why we're talking about HP lol

**Comment by vinnymac** [comment]
@hacknug just discussing features that you could easily add. This is good as it stands imo.

> Is there anything else you would like to see added to this?

**Comment by hacknug** [comment]
Now I understand haha. I meant features related to the display options this PR adds. I will draw some icons for gender and shiny like the ones in the last game update and show screenshots once I have them on my dev build then.

**Comment by vinnymac** [comment]
Their are some changes I might make to the image loading, but it looks good.

**Pull request merged**
