### PR TITLE
Evolves List

### PR DESCRIPTION
**Pull request by mackhankins**
I couldn't come up with a great way to display this data, but it returns object of possible evolves.  I would take a look at how evolvesList is built.  If you log that in the loop it creates a bunch of them, but outside you get the total count.  Needs refactor.  The .csv files are from [PokeIV](https://github.com/canele/PokeIV).

**Sample**

``` bash
[ { name: 'Eevee', count: 3, candy: 105, evolves: 3 },
  { name: 'Pidgey', count: 43, candy: 295, evolves: 24 },
  { name: 'Rattata', count: 39, candy: 334, evolves: 13 },
  { name: 'Weedle', count: 3, candy: 221, evolves: 3 },
  { name: 'Spearow', count: 14, candy: 93, evolves: 1 },
  { name: 'Caterpie', count: 9, candy: 42, evolves: 3 },
  { name: 'Poliwag', count: 2, candy: 64, evolves: 2 },
  { name: 'Bulbasaur', count: 1, candy: 32, evolves: 1 },
  { name: 'Goldeen', count: 1, candy: 50, evolves: 1 },
  { name: 'Zubat', count: 4, candy: 105, evolves: 2 },
  { name: 'Oddish', count: 2, candy: 49, evolves: 1 },
  { name: 'Bellsprout', count: 2, candy: 108, evolves: 2 },
  { name: 'Horsea', count: 1, candy: 55, evolves: 1 },
  { name: 'Staryu', count: 1, candy: 67, evolves: 1 },
  { name: 'Nidoran Male', count: 1, candy: 44, evolves: 1 },
  { name: 'Jigglypuff', count: 1, candy: 51, evolves: 1 },
  { name: 'Ekans', count: 1, candy: 57, evolves: 1 } ]
```

### CODE REVIEW

**Comment by mackhankins** [comment]
I don't think we should merge this yet obviously.  If we could get datatables into this project I have a neat idea.

**Comment by duhminick** [comment]
This looks very useful for implementing a "smart" transferring/evolving feature.  I'm relatively new to git so I'm not sure what to do.  I'll just leave this PR up for now, or put it in a different branch.  :smile:

**Comment by mackhankins** [comment]
That's probably best, you can pull my fork down to test it.  If my idea works for data tables we'll be on track then for stuff like smart evolves.

**Comment by jeckoz** [comment]
how to npm install? i installed nodejs, it didnt work

**Comment by mackhankins** [comment]
@jeckoz Try node -v to make sure you have installed because npm comes with node.

**Comment by mackhankins** [comment]
test-app

I'm making some progress, but still a few bugs to work out.

**Comment by vinnymac** [comment]
Very cool, good job 👍 

I am starting to think we should have some kind of master JSON collection. The evolutions are going to be necessary in the detail modal as well. I am going to need types, base attacks/defense, and more. Do we have a good source for this info? I saw [this](https://gist.github.com/ihciah/71b0bf44322431bd34dea4ff193267e5) but wasn't sure if something better already exists.

**Comment by mackhankins** [comment]
@vinnymac Right now what I'm doing is creating sub arrays / objects which is making that modal thing a real pain cause it can't find the pokemon, but after that I'll be ready to make a PR.  Then we can start cleaning up my sloppy code.

A master json isn't a bad idea.

**Pull request closed without merging**
