### PR TITLE
update pokemons' moves

### PR DESCRIPTION
**Pull request by Rplus**
According to `Infographic Summary of all Aug 19th Moveset Changes`
http://i.imgur.com/NuB2hWn.jpg

update(only add) some moves

### CODE REVIEW

**Comment by iPaulis** [comment]
If this updates dps and movesets #137 could be closed.

**Comment by vinnymac** [comment]
I might do a small release just for this, I haven't had time to test this pull request, anyone else able to check it out for me?

**Comment by Rplus** [comment]
@vinnymac, I update for one move updated with one commit.
I think it is better for checking.

Please squash those commits before merge.

**Comment by vinnymac** [comment]
I am not sure if this is part of your other pull request. But if we need to update the moves we should do it the same as the other one you did. Thanks again!

**Pull request closed without merging**
