### PR TITLE
Detail Modal for Pokemon

### PR DESCRIPTION
**Pull request by vinnymac**
This is a concept of how we might show detail screens for each pokemon provided we have all the data to draw it. The design is from `pogo-dex`, which is based on the games detail screen. What do you think?

Bulbasaur Detail

You can test out how this looks by trying the pull request and then clicking on any nickname will show the bulbasaur modal; just visit http://www.pogo-dex.com/pokemon/bulbasaur if you want to see how it looks.

What does everyone think about having the `Name` of the pokemon be the modal title in the upper left, and the `Nickname` would be the name below its avatar?

This is just a rough draft for some discussion to occur.

### CODE REVIEW

**Comment by mackhankins** [comment]
Why so much padding at the top?

**Comment by vinnymac** [comment]
@mackhankins that is where the CP Progress bar is. Look at the pogo site to see the original. I think the CP bar is white and so is the background so that would need to be tweaked, but so would a lot of the styles. This was only a rough draft idea thrown together to see what people would think of reusing an existing design though.

**Comment by mackhankins** [comment]
@vinnymac I like it.

**Comment by duhminick** [comment]
Thank you for your work :smile: 

This shouldn't be too hard to implement fully.

**Pull request merged**
