### PR TITLE
Modal tweaks

### PR DESCRIPTION
**Pull request by hacknug**
## Things that changed
- **Font Family:** PokéNurse uses now your system's default font family.
- **Typesetting:** Some text is now bigger and bolder. Labels are uppercase à la Pokémon GO.
- **Layout:** Some margins are now bigger, some smaller. Pokémon types are now between their weight and height à la Pokémon GO. Stats and moves sections now use flexbox to lay out their content.
- **Quick Moves:** They don't wear the ` Fast` suffix anymore.
- **Charged Moves:** Charge bars are bigger and have a flexible size.
- **Evolutions:** Space between evolutions is now bigger.

## Things I want to change change
- **Typesetting:** CP, Max CP and Pokémon name could use some
- **Header:** Name could use some work. Closing button should be bigger.
- **Meter:** Not enough contrast over some colors.
- **Stats:** Use colors or icons for Pokémon types. Too many times CP? `+30.56 CP (+/-)` `CP PER UPGRADE`. Stamina?
- **Moves:** Rename to `Charge Moves`. Show moves with STAB. Add support for legacy moves.
- **Evolutions:** Show all evolutions and their candy/item cost. Hide if no evolutions. Add second gen evolutions. Bigger images if Eeevee allows.

## Preview
img_0214
img_0213

### CODE REVIEW

**Comment by vinnymac** [comment]
In the list of things that change you said that you removed `fast` from quick moves, I don't see that change in the screenshots, was that made after? I think this looks really good.

**Comment by hacknug** [comment]
It was made after the screenshots, yup. I removed that because some names were too long and would touch the boundries of their box (and maybe some I didn't see or in the future, would break in two lines).

**Comment by hacknug** [comment]
Updated the screenshots to show how this PR alone looks like.

**Comment by vinnymac** [comment]
Looks great, thanks for these changes, users are going to love the improvements!

**Pull request merged**
