### PR TITLE
Upgrade/power up pokemon

### PR DESCRIPTION
**Pull request by SamuelMoraesF**

### CODE REVIEW

**Comment by vinnymac** [comment]
@SamuelMoraesF thanks for the PR 👍 

If you could fix the remaining lint issues I can merge this in. I think we might need a dropdown now instead of buttons since it is getting crowded, @mackhankins what do you think?

**Comment by SamuelMoraesF** [comment]
Dropdown or a button group?

IMHO, a button group should be better :)

**Comment by vinnymac** [comment]
We will have 4 buttons with this PR. Even if you used glyphs with the button group it would quickly take up too much real estate as we add more. Need a solution that will work as we add more actions.

**Comment by mackhankins** [comment]
Also need to fix the lint errors.  Most editors have some type of eslint plugin

**Comment by SamuelMoraesF** [comment]
How about a complete redesign?
screenshot from 2016-08-26 09-53-12
screenshot from 2016-08-26 09-53-40

I've made some modifications:
- Grid instead of a table
- Active status for "Toggle Caught Species" button
- Hide action buttons(transfer, evolve and upgrade) by default, and show when a Pokémon is selected with slide up effect

If you are ok with these modifications, I can do more things and open a new PR for the new layout/design.

**Comment by SamuelMoraesF** [comment]
And sorry, I've forgotten about lint. I'll fix ASAP

**Comment by mackhankins** [comment]
You should checkout the navbar branch to see what we're slowly working on there also.

**Comment by vinnymac** [comment]
@SamuelMoraesF yea I like the design, but hold off on that. Maybe we can discuss it after v1.4 is out. We already have some UI changes coming, and so I don't want to waste anyones time with that. I like the idea of the grid, especially how responsive that can be.

You should join us on discord and we can discuss more ;)

**Pull request closed without merging**
